YOLOV12:
  WEIGHT: "./detector/YOLOv12/yolov12s.pt"
  DATA: './detector/YOLOv12/ultralytics/cfg/datasets/coco.yaml'

  IMGSZ: [640, 640]
  SCORE_THRESH: 0.25
  NMS_THRESH: 0.45
  MAX_DET: 100

# 补充的DeepSort核心配置段，路径匹配你的resnet18权重，无需修改
DEEPSORT:
  REID_CKPT: ./deep_sort/deep/checkpoint/resnet18-5c106cde.pth
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.5
  MAX_IOU_DISTANCE: 0.7
  MAX_AGE: 70
  N_INIT: 3
  NN_BUDGET: 100